contacts/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import redirect_to

# Lista de url's que se utilizan en la aplicacion
urlpatterns = patterns('contacts.views',
    url(r'^login/$', 'login'),
    url(r'^disconnect/$', redirect_to, {'url':'login'}),
    url(r'^$', 'index'),
    url(r'^add/$', 'add'),
    url(r'^create/$', 'create'),
	url(r'^view/$', 'view'),
    url(r'^view/(?P<contact_id>\d+)/edit/$', 'edit'),
    url(r'^view/(?P<contact_id>\d+)/viewContact/$', 'viewContact'),
	url(r'auth/', include('social_auth.urls')),
	url (r'^view/(?P<contact_id>\d+)/delete', 'delete')
)

tp3/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.conf import settings
#from contacts.views import twitter_login, twitter_logout, twitter_authenticated

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^contacts/', include('contacts.urls')),
	(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'auth/', include('social_auth.urls')),
#	url(r'^login/?$', twitter_login),
#	url(r'^logout/?$', twitter_logout),
#	url(r'^login/authenticated/?$', twitter_authenticated),
)

contacts/models.py
# Librerias de Django
from django.db import models
from django.forms import ModelForm
from django import forms
from django.core.validators import *
from django.contrib.auth.models import User

# Librerias Externas
import oauth2 as oauth

# Se define la clase Contact, la cual representa los contactos que se ingresaran a la base de datos
class Contact(models.Model):
	name = models.CharField(max_length=200)
	lastName = models.CharField(max_length=200)
	business = models.CharField(max_length=200)
	age = models.IntegerField()
	phone = models.IntegerField()
	email = models.EmailField(max_length=200)
	longitud = models.FloatField(null=True)
	latitud = models.FloatField(null=True)

	# Este metodo se encarga de mostrar todos los campos como strings 
	def __unicode__(self):
		return self.name, self.lastName, self.business, self.age, self.phone, self.email, self.longitud, self.latitud

# Clase en la que se crea un Form para el modelo Contact
# Se define el modelo que utiliza asi como los campos que se mostran y algunas propiedades para los widgets
class ContactForm(ModelForm):
	class Meta:
		model = Contact
		fields = ('id', 'name', 'lastName', 'business', 'age', 'phone', 'email', 'longitud', 'latitud')
		widgets = {
            'name': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'lastName': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'age': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'business': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'email': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'phone': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'longitud': forms.HiddenInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'latitud': forms.HiddenInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
        }

# Clase en la que se crea un Form para el modelo Contact
# Se define el modelo que utiliza asi como los campos que se mostran y algunas propiedades para los widgets
class ContactEditForm(ModelForm):
	class Meta:
		model = Contact
		fields = ('id', 'name', 'lastName', 'business', 'age', 'phone', 'email', 'longitud', 'latitud')
		widgets = {
            'name': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'lastName': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'age': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'business': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'email': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'phone': forms.TextInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'longitud': forms.HiddenInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
            'latitud': forms.HiddenInput(attrs={'cols': 80, 'rows': 20, 'class':"text"}),
        }

contacts/views.py
# Django
from django.shortcuts import render_to_response, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import Context, loader, RequestContext
from django.forms import ModelForm
from django.forms.models import modelformset_factory
from django.core import serializers

# Aplicacion
from contacts.models import Contact, ContactForm, ContactEditForm

# Vistas
def index(request):
	contacts = serializers.serialize("json", Contact.objects.all())
	t = loader.get_template('contacts/index.html')
	c = RequestContext(request, {'contacts':contacts})
	return HttpResponse(t.render(c))

# Entradas:	request
# Proceso:	El metodo se encarga de generar el template que permite mostrar un formulario al usuario
# Salidas:	Se retorna el template al usuario
def add(request):
	formC = ContactForm(request.POST, request.FILES)
	t = loader.get_template('contacts/add.html')
	c = RequestContext(request, {'formC':formC})
	return HttpResponse(t.render(c))

# Entradas:	Se recibe un request
# Proceso:	El metodo valida los datos y se encarga de guardar los datos en la base de datos
# Salidas:	Se retorna el template para agregar contactos
def create(request):
	formC = ContactForm(request.POST)
	t = loader.get_template('contacts/add.html')
	c = RequestContext(request, {'formC':formC})
	if request.method == 'POST' and formC.is_valid():
		formC.save()
		return HttpResponseRedirect(reverse('contacts.views.add'))
	else:
		formC = ContactForm()
	return render_to_response('contacts/add.html', {'formC':formC}, context_instance=RequestContext(request))

# Entradas:	Se recibe un request y el id del contacto que se quiere modificar
# Proceso:	El metodo pregunta si el "request" que se quiere realizar es un POST, si es asi, se toman los datos del
#			form y se almacenan en la base de datos
# Salidas:	No retorna ningun valor en concreto.
def edit(request, contact_id):
	if request.method == 'POST':
		contact = Contact.objects.get(pk=contact_id)
		formC = ContactEditForm(request.POST, instance=contact)
		if formC.is_valid():
			formC.save()
		contacts = Contact.objects.all()
		t = loader.get_template('contacts/view.html')
		c = RequestContext(request, {'contacts':contacts})
		return HttpResponseRedirect(reverse('contacts.views.view'))
	else:
		contact = Contact.objects.get(pk=contact_id)
		formC = ContactEditForm(instance=contact)
		return render_to_response('contacts/edit.html', {'formC':formC}, context_instance=RequestContext(request))

# Entradas:	Se recibe un request
# Proceso:	El metodo envia a la vista la lista de todos los contactos del usuario
# Salidas:	Una variable que se pasa a la vista y que contiene todos los contactos
def view(request):
	contacts = Contact.objects.all()
	t = loader.get_template('contacts/view.html')
	c = RequestContext(request, {'contacts':contacts})
	return HttpResponse(t.render(c))

# Entradas:	Se recibe un request y el id del contacto que se quiere consultar
# Proceso:	El metodo busca el contacto consultado por medio del id
# Salidas:	Una variable que se pasa a la vista y que contiene todos los datos del contacto consultado
def viewContact(request, contact_id,):
	contact = Contact.objects.get(pk=contact_id)
	t = loader.get_template('contacts/viewContact.html')
	c = RequestContext(request, {'contact':contact})
	return HttpResponse(t.render(c))

# Entradas:	Se recibe un request y un id del contacto a eliminar
# Proceso:	El metodo busca el contacto consultado por medio del id y lo elimina
# Salidas:	Se retorna a la vista una lista con los contactos restantes. 
def delete(request, contact_id):
    Contact.objects.get(pk=contact_id).delete()
    contacts = Contact.objects.all()
    t = loader.get_template('contacts/view.html')
    c = RequestContext(request, {'contacts':contacts})
    return HttpResponse(t.render(c))

def login(request):
	return render_to_response('contacts/login.html', context_instance=RequestContext(request))

def disconnect(request):
	return render_to_response('contacts/login.html', context_instance=RequestContext(request))

templates/contacts/add.html
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		{% load staticfiles %}
		<link href="{{ STATIC_URL }}css/add.css" rel="stylesheet" type="text/css" media="all" />
		<script type="text/javascript"
			src="http://maps.google.com/maps/api/js?key=AIzaSyAqquaXVEysM4siIQGr1VAUKIqTrKW16kQ&sensor=false" >
		</script>
		{% load staticfiles %}
		<script src="{{ STATIC_URL }}js/maps.js" type="text/javascript"></script>
		<script src="{{ STATIC_URL }}js/validations.js" type="text/javascript"></script>
	</head>
	<body  onload="initialize()">
		<div id="wrapper">
			<div id="menu">
				{% url contacts.views.index as indexC %}
				<a id="menuLink" href="{{ indexC }}">Inicio</a>
				{% url contacts.views.view as viewC %}
				<a id="menuLink" href="{{ viewC }}">Ver Contactos</a>
			</div>
			<div id="instructions">
				<h1>Agregar Contacto</h1>
				<ul>
					<li>Utilice el siguiente formulario para agregar nuevos contactos.</li>
					<li>Haga clic en el mapa para colocar un marcador que corresponderá a la dirección del nuevo contacto. Si desea cambiar la posición del marcador, solo arrastre el marcador a la posición que desea</li>
				</ul>
			</div>
			<div id="form">
				<form name="form" action="/contacts/create/" method="POST">{% csrf_token %}
					{% block form %}
						<div class="input">
							<label class="label" for="id_name">Nombre: </label>
							{{ formC.name }}
						</div>
						<div class="input">
							<label class="label" for="id_lastName">Apellidos: </label>
							{{ formC.lastName }}
						</div>
						<div class="input">
							<label class="label" for="id_phone">Teléfono: </label>
							{{ formC.phone }}
						</div>
						<div class="input">
							<label class="label" for="id_age">Edad: </label>
							{{ formC.age }}
						</div>
						<div class="input">
							<label class="label" for="id_business">Empresa: </label>
							{{ formC.business }}
						</div>
						<div class="input">
							<label class="label" for="id_email">Correo Electrónico: </label>
							{{ formC.email }}
						</div>
						<div class="input" style="display:hidden;">
							<label class="label" for="id_latitud" style="display:none;">Latitud: </label>
							{{ formC.latitud }}
						</div>
						<div class="input" style="display:hidden;">
							<label class="label" for="id_longitud" style="display:none;">Longitud: </label>
							{{ formC.longitud }}
						</div>
						<div id="errores">
						</div>
						<div class="input" id="button">
							{% url contacts.views.index as index %}<a href="{{ index }}">Volver</a> |
							<input id="id_button" class="button" type="submit" value="Agregar" />
						</div>
					{% endblock %}
				</form>
			</div>
			<div id="map_canvas"></div>
		</div>
	</body>
</html>

templates/contacts/edit.html
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		{% load staticfiles %}
		<link href="{{ STATIC_URL }}css/edit.css" rel="stylesheet" type="text/css" media="all" />
		<script type="text/javascript"
			src="http://maps.google.com/maps/api/js?key=AIzaSyAqquaXVEysM4siIQGr1VAUKIqTrKW16kQ&sensor=false" >
		</script>
		{% load staticfiles %}
		<script src="{{ STATIC_URL }}js/maps.js" type="text/javascript"></script>
	</head>
	<body  onload="initialize()">
		<div id="wrapper">
			<div id="menu">
				{% url contacts.views.index as indexC %}
				<a id="menuLink" href="{{ indexC }}">Inicio</a>
				{% url contacts.views.view as viewC %}
				<a id="menuLink" href="{{ viewC }}">Volver</a>
			</div>
			<div id="instructions">
				<h1>Editar Contacto</h1>
				<p>
					Utilice el siguiente formulario para editar contacto.
				</p>
				<br/>
			</div>
			<div id="form">
				<form action="." method="POST">{% csrf_token %}
					{% block form %}
						<div class="input" style="display:hidden;">
							<label class="label" for="id_longitud" style="display:none;">Longitud: </label>
							{{ formC.id }}
						</div>
						<div class="input">
							<label class="label" for="id_name">Nombre: </label>
							{{ formC.name }}
						</div>
						<div class="input">
							<label class="label" for="id_lastName">Apellidos: </label>
							{{ formC.lastName }}
						</div>
						<div class="input">
							<label class="label" for="id_phone">Teléfono: </label>
							{{ formC.phone }}
						</div>
						<div class="input">
							<label class="label" for="id_age">Edad: </label>
							{{ formC.age }}
						</div>
						<div class="input">
							<label class="label" for="id_business">Empresa: </label>
							{{ formC.business }}
						</div>
						<div class="input">
							<label class="label" for="id_email">Correo Electrónico: </label>
							{{ formC.email }}
						</div>
						<div class="input" style="display:hidden;">
							<label class="label" for="id_latitud" style="display:none;">Latitud: </label>
							{{ formC.latitud }}
						</div>
						<div class="input" style="display:hidden;">
							<label class="label" for="id_longitud" style="display:none;">Longitud: </label>
							{{ formC.longitud }}
						</div>
						<div class="input" id="button">
							{% url contacts.views.view as view %}<a href="{{ view }}">Volver</a> |
							<input class="button" type="submit" value="Guardar" />
						</div>
					{% endblock %}
				</form>
			</div>
			<div id="map_canvas"></div>
		</div>
	</body>
</html>

templates/contacts/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		{% load staticfiles %}
		<link href="{{ STATIC_URL }}css/index.css" rel="stylesheet" type="text/css" media="all" />
		<script type="text/javascript"
			src="http://maps.google.com/maps/api/js?key=AIzaSyAqquaXVEysM4siIQGr1VAUKIqTrKW16kQ&sensor=false" >
		</script>
		{% load staticfiles %}
		<script src="{{ STATIC_URL }}js/index.js" type="text/javascript"></script>
	</head>
	<body onload="initialize()" >
		<div id="wrapper">
			<div id="menu">
				{% url contacts.views.add as addC %}
				<a href="{{ addC }}">Agregar Contactos</a>)
				<a href="{% url socialauth_disconnect 'twitter' %}?=next{% url contacts.views.login %}">Salir del Sistema</a>
			</div>
			<div id="table">
				{% block contacts %}
					<script type="text/javascript">
						var json = "{{ contacts|escapejs }}";
						var parsed_json = JSON.parse(json);
						getData(parsed_json);
					</script>
				{% endblock %}
			</div>
			<div id="map_canvas">
			</div>
		</div>
	</body>
</html>

templates/contacts/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		{% load staticfiles %}
		<link href="{{ STATIC_URL }}css/index.css" rel="stylesheet" type="text/css" media="all" />
		<script type="text/javascript"
			src="http://maps.google.com/maps/api/js?key=AIzaSyAqquaXVEysM4siIQGr1VAUKIqTrKW16kQ&sensor=false" >
		</script>
		{% load staticfiles %}
		<script src="{{ STATIC_URL }}js/index.js" type="text/javascript"></script>
	</head>
	<body onload="initialize()" >
		<div id="wrapper">
			<div id="menu">
				<a href="{% url socialauth_begin 'twitter' %}">Ingresar usando Twitter</a>
			</div>
			<div id="map_canvas">
			</div>
		</div>
	</body>
</html>

templates/contacts/search.html
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		{% load staticfiles %}
		<link href="{{ STATIC_URL }}css/add.css" rel="stylesheet" type="text/css" media="all" />
		<script type="text/javascript"
			src="http://maps.google.com/maps/api/js?key=AIzaSyAqquaXVEysM4siIQGr1VAUKIqTrKW16kQ&sensor=false" >
		</script>
		{% load staticfiles %}
		<script src="{{ STATIC_URL }}js/maps.js" type="text/javascript"></script>
	</head>
	<body  onload="initialize()">
		<div id="wrapper">
			<div id="menu">
				{% url contacts.views.index as indexC %}
				<a id="menuLink" href="{{ indexC }}">Inicio</a>
				{% url contacts.views.view as viewC %}
				<a id="menuLink" href="{{ viewC }}">Ver Contactos</a>
			</div>
			<div id="instructions">
				<h1>Agregar Contacto</h1>
				<ul>
					<li>Utilice el siguiente formulario para agregar nuevos contactos.</li>
					<li>Haga clic en el mapa para colocar un marcador que corresponderá a la dirección del nuevo contacto. Si desea cambiar la posición del marcador, solo arrastre el marcador a la posición que desea</li>
				</ul>
			</div>
			<div id="form">
				<form action="/contacts/create/" method="POST">{% csrf_token %}
				</form>
			</div>
			<div id="map_canvas"></div>
		</div>
	</body>
</html>

templates/contacts/view.html
<!DOCTYPE html>
<html>
	<head>
		{% load staticfiles %}
		<link href="{{ STATIC_URL }}css/view.css" rel="stylesheet" type="text/css" media="all" />
	</head>
	<body>
		<div id="wrapper">
			<div id="menu">
				{% url contacts.views.index as indexC %}
				<a id="menuLink" href="{{ indexC }}">Inicio</a>
				{% url contacts.views.add as addC %}
				<a id="menuLink" href="{{ addC }}">Volver</a>
			</div>
			<div id="table">
				<table>
					<tr>
						<th> Nombre </th>
						<th> Teléfono </th>
						<th> Correo Electronico </th>
						<th> Opciones </th>
					</tr>
					{% if contacts %}
						{% for contact in contacts %}
							<tr>
								<td> {{ contact.name }} {{ contact.lastName }} </td>
								<td> {{ contact.phone }} </td>
								<td> {{ contact.email }} </td>
								<td>
									<a href="{{ contact.id }}/edit">Editar</a> |
									<a href="{{ contact.id }}/viewContact">Ver</a> | 
									<a href="{{ contact.id }}/delete">Eliminar</a>
								</td>
							</tr>
						{% endfor %}
					{% else %}
						<p>No hay contactos para mostrar</p>
					{% endif %}
				</table>
			</div>
			<div id="map_canvas">
			</div>
		</div>
	</body>
</html>

templates/contacts/viewContact.html
<!DOCTYPE html>
<html>
	<head>
		{% load staticfiles %}
		<link href="{{ STATIC_URL }}css/viewContact.css" rel="stylesheet" type="text/css" media="all" />
	</head>
	<body>
		<div id="wrapper">
			<div id="menu">
				{% url contacts.views.index as indexC %}
				<a id="menuLink" href="{{ indexC }}">Inicio</a>
				{% url contacts.views.view as viewC %}
				<a id="menuLink" href="{{ viewC }}">Volver</a>
			</div>
			<div id="info">
				{% if contact %}
					<p><span>Nombre:</span> {{ contact.name }}</p>
					<p><span>Apellido:</span> {{ contact.lastName }}</p>
					<p><span>Teléfono:</span> {{ contact.phone }}</p>
					<p><span>Edad:</span> {{ contact.age }}</p>
					<p><span>Correo Electrónico:</span> {{ contact.email }}</p>
					<p><span>Empresa:</span> {{ contact.business }}</p>
				{% else %}
					<p>No hay información del contacto</p>
				{% endif %}
			</div>
		</div>
	</body>
</html>